---
title: "ChIP-data Randomization (Figure 2 g-h and Supp. Figure 6 f-g)"
author: "-"
date: "2023-06-26"
output: html_document
---

```{r}
library(stringr)
library(dplyr)
library(readxl)
require('igraph')
require('reshape2')
require('ggplot2')
library(dplyr)
library(stringr)
library(writexl)
#BiocManager::install("TFBSTools")
library(readxl)
library(matrixStats)
library(stringi)
library(Biostrings)
library(TFBSTools)
library(TFMPvalue)
library(readr)

# TFs with chip-seq information

htfs = read.delim('all_tfs_chipseq.txt', sep = '\t')

metadata = read.delim('ChIP-seq.metadata.txt', sep = '\t')

metadata = metadata %>% 
  filter(specie == 'Homo sapiens') %>% 
  filter(tf_uniprot_id %in% htfs$Uniprot)

metadata$TF = htfs$ID[match(metadata$tf_uniprot_id, htfs$Uniprot)]

chip_data = read_table('all_tfs_chipseq.txt')
chip_data = rbind(chip_data, data.frame(ID = 'TFAP2A', Uniprot = 'P05549'))

y1h_data = read_excel('Final events list 6FEB23.xlsx')
y1h_data = y1h_data[,c(-6)]

info = c()
for(i in 1:nrow(y1h_data)){
  tf1 = y1h_data[i,1] %>% unlist()
  tf2 = y1h_data[i,2] %>% unlist()
  
  if(tf1 %in% chip_data$ID & tf2 %in% chip_data$ID){
    info = c(info, 3)
  } else if (tf1 %in% chip_data$ID){
    info = c(info, 1)
  } else if (tf2 %in% chip_data$ID){
    info = c(info, 2)
  } else{
    info = c(info, 0)
  }
}

y1h_data$CHIP_info = info


peaks_data = read_excel('MACS2_Peaks_TFs_final_16_feb.xlsx')


both_data = y1h_data %>% 
  filter(CHIP_info == 3)

n_in_same_cell_line_tested = c()
in_same_promoter = c()
in_same_cell_line = c()
n_cell_line_1 = c()
n_cell_line_2 = c()
n_cell_line_1_tested_column = c()
n_cell_line_2_tested_column = c()

all_min_differences = c()

for(i in 1:nrow(both_data)){
  tf1 = both_data[i,1] %>% unlist()
  tf2 = both_data[i,2] %>% unlist()
  promoter = both_data[i,3] %>% unlist()
  
  n_cell_line_1_tested = metadata %>% filter(TF == tf1) %>% dplyr::select(title) %>% unlist() %>% unique()
  n_cell_line_2_tested = metadata %>% filter(TF == tf2) %>% dplyr::select(title) %>% unlist() %>% unique()
  
  n_cell_line_1_tested_column = c(n_cell_line_1_tested_column, length(n_cell_line_1_tested))
  n_cell_line_2_tested_column = c(n_cell_line_2_tested_column, length(n_cell_line_2_tested))
  
  n_cell_line_both_tested = intersect(n_cell_line_1_tested, n_cell_line_2_tested)
  
  if(!is.null(n_cell_line_both_tested) & length(n_cell_line_both_tested) > 0){
    n_in_same_cell_line_tested = c(n_in_same_cell_line_tested, length(n_cell_line_both_tested))
  } else{
    n_in_same_cell_line_tested = c(n_in_same_cell_line_tested, 0)
  }

  subdf = peaks_data %>% filter(name %in% c(tf1,tf2), cytokine == promoter)
  
  n_tfs = subdf$name %>% unlist() %>% unique() %>% length()
  
  if(n_tfs == 0){
    in_same_promoter = c(in_same_promoter, 0)
    n_cell_line_1 = c(n_cell_line_1, NA)
    n_cell_line_2 = c(n_cell_line_2, NA)
    in_same_cell_line = c(in_same_cell_line, NA)
    min_differences = NA
  } else if(n_tfs == 2){
    
    in_same_promoter = c(in_same_promoter, 3)
    
    info1 = peaks_data %>% filter(name == tf1, cytokine == promoter) %>% dplyr::select(cell_line) %>% unlist() %>% unique()
    info2 = peaks_data %>% filter(name == tf2, cytokine == promoter) %>% dplyr::select(cell_line) %>% unlist() %>% unique()
    
    n_cell_line_1 = c(n_cell_line_1, length(intersect(n_cell_line_both_tested, info1)))
    n_cell_line_2 = c(n_cell_line_2, length(intersect(n_cell_line_both_tested, info2)))
    
    n_intersect_cell_lines = intersect(info1, info2)
    
    if(!is.null(n_intersect_cell_lines) & length(n_intersect_cell_lines) > 0){
      in_same_cell_line = c(in_same_cell_line, length(n_intersect_cell_lines))
      min_differences = c()
      for (cell.line in n_intersect_cell_lines){
        tmp.df = subdf %>% filter(cell_line == cell.line)
        peaks_1 = tmp.df %>% filter(name == tf1) %>% dplyr::select(abs_summit) %>% unlist()
        peaks_2 = tmp.df %>% filter(name == tf2) %>% dplyr::select(abs_summit) %>% unlist()
        differences = apply(tidyr::crossing(peaks_1, peaks_2), 1, diff)
        differences = min(abs(differences))
        min_differences = c(min_differences, differences)
      }
      min_differences = paste0(min_differences, collapse=',')
      
    } else{
      in_same_cell_line = c(in_same_cell_line, 0)
      min_differences = c()
      tmp.df = subdf
      peaks_1 = tmp.df %>% filter(name == tf1) %>% dplyr::select(abs_summit) %>% unlist()
      peaks_2 = tmp.df %>% filter(name == tf2) %>% dplyr::select(abs_summit) %>% unlist()
      differences = apply(tidyr::crossing(peaks_1, peaks_2), 1, diff)
      differences = min(abs(differences))
      min_differences = c(min_differences, differences)
      min_differences = paste0(min_differences, collapse=',')
      
    }
    
  } else if (n_tfs == 1 & subdf$name %>% unlist() %>% unique() == tf1){
    in_same_promoter = c(in_same_promoter, 1)
    
    info1 = peaks_data %>% filter(name == tf1, cytokine == promoter) %>% dplyr::select(cell_line) %>% unlist() %>% unique()
    n_cell_line_1 = c(n_cell_line_1, length(intersect(n_cell_line_both_tested, info1)))
    n_cell_line_2 = c(n_cell_line_2, NA)
    in_same_cell_line = c(in_same_cell_line, NA)
    min_differences = NA
    
  } else if (n_tfs == 1 & subdf$name %>% unlist() %>% unique() == tf2){
    in_same_promoter = c(in_same_promoter, 2)
    n_cell_line_1 = c(n_cell_line_1, NA)
    info2 = peaks_data %>% filter(name == tf2, cytokine == promoter) %>% dplyr::select(cell_line) %>% unlist() %>% unique()
    n_cell_line_2 = c(n_cell_line_2, length(intersect(n_cell_line_both_tested, info2)))
    in_same_cell_line = c(in_same_cell_line, NA)
    min_differences = NA
  } 
  
  all_min_differences = c(all_min_differences, min_differences)
}

both_data$in_same_promoter = in_same_promoter
both_data$n_cell_line_1_tested_column = n_cell_line_1_tested_column
both_data$n_cell_line_2_tested_column = n_cell_line_2_tested_column
both_data$n_in_same_cell_line_tested = n_in_same_cell_line_tested
both_data$n_cell_line_1 = n_cell_line_1
both_data$n_cell_line_2 = n_cell_line_2
both_data$in_same_cell_line = in_same_cell_line
both_data$Peaks_Distances = all_min_differences
colnames(both_data) = c('TF1', 'TF2', 'DNA bait', 'DNA bait ID', 'DNA bait sequence', 'has_Chip_seq_info?', 'has_chip_in_same_promoter?', 'n_cell_lines_TF1_tested', 'n_cell_lines_TF2_tested', 'n_cell_lines_both_tested', 'n_cell_lines_TF1_chip', 'n_cell_lines_TF2_chip','n_cell_lines_both_chip'  ,'Peaks_Distances')

info = read_excel('Final events list 6Feb23.xlsx')
info = info %>% 
  group_by(TF1, TF2, `DNA bait`) %>% 
  mutate(joined = paste(TF1, TF2, `DNA bait`, sep = '-'))

both_data$event_type = info$`event type`[match(paste(both_data$TF1, both_data$TF2, both_data$`DNA bait`, sep ='-'), info$joined)]
both_data$who_TF = str_split_fixed(both_data$event_type, pattern = ' ', n = 2)[,1]
both_data$event_type = ifelse(both_data$event_type != 'cooperativity', 'antagonism', 'cooperativity')

#write_xlsx(both_data, 'Peaks_analyses_results_16FEB_2.xlsx')
```

```{r}

## Plots and numbers
both_data = as.data.frame(both_data)
both_data[is.na(both_data)] = 0

table(both_data$event_type)


both_data %>% filter(event_type == 'cooperativity') %>% group_by(`has_chip_in_same_promoter?`) %>% summarize(n = n())


both_data %>% mutate(n_tfs = ifelse(`has_chip_in_same_promoter?` == 3, 2,
                                    ifelse( `has_chip_in_same_promoter?` == 2 | `has_chip_in_same_promoter?` == 1, 1, 0))) %>% 
  filter(event_type == 'cooperativity') %>% 
  group_by(n_tfs) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = '', y = n , fill = as.factor(n_tfs))) +
  geom_bar(stat = 'identity', width = 1, color= 'white') +
  coord_polar('y', start = 0) + theme_void() + ggtitle('Cooperative different cell line')

both_data %>% mutate(n_tfs = ifelse(`has_chip_in_same_promoter?` == 3, 2,
                                    ifelse( `has_chip_in_same_promoter?` == 2 | `has_chip_in_same_promoter?` == 1, 1, 0))) %>% 
  filter(event_type == 'antagonism') %>% 
  group_by(n_tfs) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = '', y = n , fill = as.factor(n_tfs))) +
  geom_bar(stat = 'identity', width = 1, color= 'white') +
  coord_polar('y', start = 0) + theme_void() + ggtitle('Antagonism different cell line')



both_data %>% mutate(n_tfs = ifelse(n_cell_lines_TF1_chip > 0 & n_cell_lines_TF2_chip > 0 & n_cell_lines_both_chip > 0, 2 ,
                                    ifelse( (n_cell_lines_TF1_chip > 0  & n_cell_lines_TF2_chip == 0) | (n_cell_lines_TF1_chip == 0  & n_cell_lines_TF2_chip > 0) , 1, 0))) %>%
  mutate(n_tfs = ifelse(is.na(n_tfs), 0 , n_tfs)) %>% 
  filter(event_type == 'cooperativity') %>% 
  filter(n_cell_lines_both_tested > 0) %>% 
  group_by(n_tfs) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = '', y = n , fill = as.factor(n_tfs))) +
  geom_bar(stat = 'identity', width = 1, color= 'white') +
  coord_polar('y', start = 0) + theme_void() + ggtitle('Cooperative same cell line')
 

both_data %>% mutate(n_tfs = ifelse(n_cell_lines_TF1_chip > 0 & n_cell_lines_TF2_chip > 0 & n_cell_lines_both_chip > 0, 2 ,
                                    ifelse( (n_cell_lines_TF1_chip > 0  & n_cell_lines_TF2_chip == 0) | (n_cell_lines_TF1_chip == 0  & n_cell_lines_TF2_chip > 0), 1, 0))) %>%
  mutate(n_tfs = ifelse(is.na(n_tfs), 0 , n_tfs)) %>% 
  filter(event_type == 'antagonism') %>% 
  filter(n_cell_lines_both_tested > 0) %>% 
  group_by(n_tfs) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = '', y = n , fill = as.factor(n_tfs))) +
  geom_bar(stat = 'identity', width = 1, color= 'white') +
  coord_polar('y', start = 0) + theme_void() + ggtitle('Antagonism same cell line')

```


```{r}
## Ordering PY1H dataframe
y1h_data = read_excel('Final events list 6Feb23.xlsx')
tfx = c()
tfy = c()
for(i in 1:nrow(y1h_data)){
  tf1 = y1h_data[i, 'TF1'] %>% unlist()
  tf2 = y1h_data[i, 'TF2'] %>% unlist()
  if(tf1 < tf2){
    tfx = c(tfx, tf1)
    tfy = c(tfy, tf2)
  } else{
    tfx = c(tfx, tf2)
    tfy = c(tfy, tf1)
  }
}
y1h_data$TF1 = tfx
y1h_data$TF2 = tfy
y1h_data$name = paste(y1h_data$TF1, '-', y1h_data$TF2, '-', y1h_data$`DNA bait`, sep ='')
y1h_data$name2 = paste(y1h_data$TF1, '-', y1h_data$TF2, sep ='')
```


```{r}
## Randomization only cooperative (all cell lines)

htfs = read.delim('all_tfs_chipseq.txt', sep = '\t')
htfs = rbind(htfs, data.frame(ID = 'AP2A', Uniprot = 'P05549'))
htfs = rbind(htfs, data.frame(ID = 'TFAP2A', Uniprot = 'P05549'))

# Number of TFs with CHIP-seq data
tfs_in_chip = htfs$ID %>% unique()

### YEAST ONE HYBRID DATA
y1h_data = read_excel('Final events list 6FEB23.xlsx')

y1h_data = y1h_data %>% 
  filter(`event type` == 'cooperativity') %>% 
  group_by(TF1, TF2, `DNA bait`) %>% 
  mutate(name = paste(min(TF1,TF2), '-',max(TF1,TF2), ';', `DNA bait`, sep = '' ),
         name2 = paste(min(TF1,TF2), '-',max(TF1,TF2), sep = '' ))


# Number of TFs with Y1H data
tfs_in_y1h = c(y1h_data$TF1, y1h_data$TF2) %>% unique()

## Get intersection of TFs
tfs_in_both = intersect(tfs_in_chip, tfs_in_y1h)

## Filtering Y1H with TFs with CHIP-seq info
y1h_data = y1h_data %>% filter(TF1 %in% tfs_in_both & TF2 %in%tfs_in_both)

## PEAKS DATA
peaks_data = read_excel('MACS2_Peaks_TFs_final_16_feb.xlsx')


# Add protein id to uniprot id
peaks_data$TF = htfs$ID[match(peaks_data$uniprot_id, htfs$Uniprot)]
peaks_data$TF = peaks_data$name

# Create CHIP seq network
peaks_df = data.frame()
for(Cytokine in peaks_data$cytokine %>% unique()){
  tmp.peaks_data = peaks_data %>% filter(cytokine == Cytokine)
  info.1 = paste(tmp.peaks_data$name, '-', tmp.peaks_data$abs_summit,sep ='') %>% unique()
  tmp.df = tidyr::crossing(info.1, info.1)
  tmp.df$TF1 = str_split_fixed(tmp.df$info.1...1, '-', 2)[,1]
  tmp.df$summit1 = as.numeric(str_split_fixed(tmp.df$info.1...1, '-', 2)[,2])
  tmp.df$TF2 = str_split_fixed(tmp.df$info.1...2, '-', 2)[,1]
  tmp.df$summit2 = as.numeric(str_split_fixed(tmp.df$info.1...2, '-', 2)[,2])
  tmp.df = tmp.df %>% dplyr::select(-1,-2)
  tmp.df = tmp.df %>% filter(TF1 != TF2)
  tmp.df$distances = abs(tmp.df$summit1 - tmp.df$summit2)
  tmp.df = tmp.df %>% group_by(TF1,TF2) %>% 
    summarize(distance = min(distances)) %>% 
    group_by(TF1,TF2) %>% 
    mutate(tf1x = min(TF1, TF2),
           tf2x = max(TF1, TF2)) %>% 
    ungroup() %>% 
    dplyr::select(-1, -2) %>% 
    unique()
  

  tmp.df$cytokine = Cytokine
  tmp.df = tmp.df[, c('tf1x', 'tf2x', 'cytokine', 'distance')]
  colnames(tmp.df) = c('TF1', 'TF2', 'cytokine', 'distance')
  peaks_df = rbind(peaks_df, tmp.df)

}
  

## Filter step
cutoff.distance = 50
peaks_df2 = peaks_df %>% group_by(TF1, TF2, cytokine) %>% summarize(distance = min(distance))

peaks_df2 = peaks_df2 %>% filter(distance <= cutoff.distance)
peaks_df2 = unique(peaks_df2)

# Create CHIP seq network
peaks_df2 = peaks_df2 %>% 
  group_by(TF1, TF2, cytokine) %>% 
  mutate(name = paste(min(TF1,TF2), '-',max(TF1,TF2), ';', cytokine, sep = '' ),
         name2 = paste(min(TF1,TF2), '-',max(TF1,TF2), sep = '' ))


## Y1H data with CHIP-seq data
merge(y1h_data, peaks_df2, by ='name') %>% dim()

# Y1H Network with 343 edges
test_network = graph_from_data_frame(y1h_data[,c('name2','DNA bait')])

# CHIP Network with 14462 edges
reference_network = graph_from_data_frame(peaks_df2[, c('name2', 'cytokine')])

## True = CHIP edges
true = as_adjacency_matrix(reference_network,sparse = F)
true = melt(true)
true = true[true$value==1,]
true = paste0(true$Var1,true$Var2)

## Real_result
real_info = as_adjacency_matrix(test_network,sparse = F)
real_info = melt(real_info)
real_info = real_info[real_info$value==1,]
real_info = paste0(real_info$Var1,real_info$Var2)
length(intersect(true, real_info))


numberofedgeswitching = 20000
iteration = 10000

results = c()

for (i in 1:iteration) {
  randomized_network = rewire(test_network, keeping_degseq(niter = numberofedgeswitching))
  randomized = as_adjacency_matrix(randomized_network,sparse = F)
  randomized = melt(randomized)
  randomized = randomized[randomized$value==1,]
  randomized = paste0(randomized$Var1,randomized$Var2)
  results = c(results,length(intersect(true,randomized)))
}

real_number = length(intersect(true, real_info))
results = data.frame(overlap=c(results, real_number),identity=c(rep('Randomized',iteration),'True'))
mean_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% mean()
sd_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% sd()
zscore = (real_number - mean_results)/ sd_results

ggplot(results,aes(x=overlap))+
  geom_histogram(binwidth = 1, color = 'black')+
  geom_vline(xintercept = results$overlap[results$identity=='True'],colour='red') +
  theme_bw() + 
  ggtitle('Cooperativity')

#writexl::write_xlsx(results, path = 'Results_diff_cell_lines_16_feb_cooperativity_50_nts_distance.xlsx')

```


```{r}

## Randomization only antagonism (all cell lines)

htfs = read.delim('all_tfs_chipseq.txt', sep = '\t')
htfs = rbind(htfs, data.frame(ID = 'AP2A', Uniprot = 'P05549'))
htfs = rbind(htfs, data.frame(ID = 'TFAP2A', Uniprot = 'P05549'))

# Number of TFs with CHIP-seq data
tfs_in_chip = htfs$ID %>% unique()

### YEAST ONE HYBRID DATA
y1h_data = read_excel('Final events list 6FEB23.xlsx')

y1h_data = y1h_data %>% 
  filter(`event type` != 'cooperativity') %>% 
  group_by(TF1, TF2, `DNA bait`) %>% 
  mutate(name = paste(min(TF1,TF2), '-',max(TF1,TF2), ';', `DNA bait`, sep = '' ),
         name2 = paste(min(TF1,TF2), '-',max(TF1,TF2), sep = '' ))


# Number of TFs with Y1H data
tfs_in_y1h = c(y1h_data$TF1, y1h_data$TF2) %>% unique()

## Get intersection of TFs
tfs_in_both = intersect(tfs_in_chip, tfs_in_y1h)

## Filtering Y1H with TFs with CHIP-seq info
y1h_data = y1h_data %>% filter(TF1 %in% tfs_in_both & TF2 %in%tfs_in_both)
dim(y1h_data)

## PEAKS DATA
peaks_data = read_excel('MACS2_Peaks_TFs_final_16_feb.xlsx')


# Add protein id to uniprot id
peaks_data$TF = htfs$ID[match(peaks_data$uniprot_id, htfs$Uniprot)]
peaks_data$TF = peaks_data$name

# Create CHIP seq network
peaks_df = data.frame()
for(Cytokine in peaks_data$cytokine %>% unique()){
  tmp.peaks_data = peaks_data %>% filter(cytokine == Cytokine)
  info.1 = paste(tmp.peaks_data$name, '-', tmp.peaks_data$abs_summit,sep ='') %>% unique()
  tmp.df = tidyr::crossing(info.1, info.1)
  tmp.df$TF1 = str_split_fixed(tmp.df$info.1...1, '-', 2)[,1]
  tmp.df$summit1 = as.numeric(str_split_fixed(tmp.df$info.1...1, '-', 2)[,2])
  tmp.df$TF2 = str_split_fixed(tmp.df$info.1...2, '-', 2)[,1]
  tmp.df$summit2 = as.numeric(str_split_fixed(tmp.df$info.1...2, '-', 2)[,2])
  tmp.df = tmp.df %>% dplyr::select(-1,-2)
  tmp.df = tmp.df %>% filter(TF1 != TF2)
  tmp.df$distances = abs(tmp.df$summit1 - tmp.df$summit2)
  tmp.df = tmp.df %>% group_by(TF1,TF2) %>% 
    summarize(distance = min(distances)) %>% 
    group_by(TF1,TF2) %>% 
    mutate(tf1x = min(TF1, TF2),
           tf2x = max(TF1, TF2)) %>% 
    ungroup() %>% 
    dplyr::select(-1, -2) %>% 
    unique()
  

  tmp.df$cytokine = Cytokine
  tmp.df = tmp.df[, c('tf1x', 'tf2x', 'cytokine', 'distance')]
  colnames(tmp.df) = c('TF1', 'TF2', 'cytokine', 'distance')
  peaks_df = rbind(peaks_df, tmp.df)

}
  

## Filter step
cutoff.distance = 50
peaks_df2 = peaks_df %>% group_by(TF1, TF2, cytokine) %>% summarize(distance = min(distance))

peaks_df2 = peaks_df2 %>% filter(distance <= cutoff.distance)
peaks_df2 = unique(peaks_df2)

# Create CHIP seq network
peaks_df2 = peaks_df2 %>% 
  group_by(TF1, TF2, cytokine) %>% 
  mutate(name = paste(min(TF1,TF2), '-',max(TF1,TF2), ';', cytokine, sep = '' ),
         name2 = paste(min(TF1,TF2), '-',max(TF1,TF2), sep = '' ))


## Y1H data with CHIP-seq data
merge(y1h_data, peaks_df2, by ='name') %>% dim()

# Y1H Network with 343 edges
test_network = graph_from_data_frame(y1h_data[,c('name2','DNA bait')])

# CHIP Network with 14462 edges
reference_network = graph_from_data_frame(peaks_df2[, c('name2', 'cytokine')])

## True = CHIP edges
true = as_adjacency_matrix(reference_network,sparse = F)
true = melt(true)
true = true[true$value==1,]
true = paste0(true$Var1,true$Var2)

## Real_result
real_info = as_adjacency_matrix(test_network,sparse = F)
real_info = melt(real_info)
real_info = real_info[real_info$value==1,]
real_info = paste0(real_info$Var1,real_info$Var2)


numberofedgeswitching = 20000
iteration = 10000

results = c()

for (i in 1:iteration) {
  randomized_network = rewire(test_network, keeping_degseq(niter = numberofedgeswitching))
  randomized = as_adjacency_matrix(randomized_network,sparse = F)
  randomized = melt(randomized)
  randomized = randomized[randomized$value==1,]
  randomized = paste0(randomized$Var1,randomized$Var2)
  results = c(results,length(intersect(true,randomized)))
}

real_number = length(intersect(true, real_info))
results = data.frame(overlap=c(results, real_number),identity=c(rep('Randomized',iteration),'True'))
mean_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% mean()
sd_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% sd()
zscore = (real_number - mean_results)/ sd_results

ggplot(results,aes(x=overlap))+
  geom_histogram(binwidth = 1, color = 'black')+
  geom_vline(xintercept = results$overlap[results$identity=='True'],colour='red') +
  theme_bw() + 
  ggtitle('Antagonism')

#writexl::write_xlsx(results, path = 'Results_diff_cell_lines_16_feb_antagonism_50_nts_distance.xlsx')
```
```{r}
## Randomization in same cell lines

htfs = read.delim('all_tfs_chipseq.txt', sep = '\t')
htfs = rbind(htfs, data.frame(ID = 'AP2A', Uniprot = 'P05549'))
htfs = rbind(htfs, data.frame(ID = 'TFAP2A', Uniprot = 'P05549'))

# Number of TFs with CHIP-seq data
tfs_in_chip = htfs$ID %>% unique()

### YEAST ONE HYBRID DATA
y1h_data = read_excel('Final events list 6FEB23.xlsx')
y1h_data = y1h_data %>% 
  filter(`event type` == 'cooperativity') %>% 
  #dplyr::select(-4, -5) %>% 
  group_by(TF1, TF2, `DNA bait`) %>% 
  mutate(name = paste(min(TF1,TF2), '-',max(TF1,TF2), ';', `DNA bait`, sep = '' ),
         name2 = paste(min(TF1,TF2), '-',max(TF1,TF2), sep = '' ))

# Number of TFs with Y1H data
tfs_in_y1h = c(y1h_data$TF1, y1h_data$TF2) %>% unique()

## Get intersection of TFs
tfs_in_both = intersect(tfs_in_chip, tfs_in_y1h)
#tfs_in_both = tfs_in_y1h

## Filtering Y1H with TFs with CHIP-seq info
y1h_data = y1h_data %>% filter(TF1 %in% tfs_in_both & TF2 %in%tfs_in_both)


## PEAKS DATA
peaks_data = read_excel('MACS2_Peaks_TFs_final_16_feb.xlsx')

# Add protein id to uniprot id
peaks_data$TF = htfs$ID[match(peaks_data$uniprot_id, htfs$Uniprot)]


### Check that only works with same cell-line
# Create CHIP seq network
tmp_peaks = peaks_data %>% 
  filter(TF %in% tfs_in_both) %>% 
  group_by(cytokine, cell_line) %>% 
  summarize(tfs = paste(TF %>% unique(), collapse =',')) %>% 
  filter(str_count(tfs, ',') > 0)

peaks_df = data.frame()
i = 2
for(i in 1:nrow(tmp_peaks)){
  tfs = tmp_peaks[i,3] %>% unlist() %>% str_split(',') %>% unlist()
  Cytokine = tmp_peaks[i,1] %>% unlist()
  cell.line = tmp_peaks[i,2] %>% unlist()
  tmp.peaks = peaks_data %>% filter(name %in% tfs) %>% filter(cytokine == Cytokine) %>% filter(cell_line == cell.line)
  info.1 = paste(tmp.peaks$name, '-', tmp.peaks$abs_summit,sep ='') %>% unique()
  tmp.df = tidyr::crossing(info.1, info.1)
  tmp.df$TF1 = str_split_fixed(tmp.df$info.1...1, '-', 2)[,1]
  tmp.df$summit1 = as.numeric(str_split_fixed(tmp.df$info.1...1, '-', 2)[,2])
  tmp.df$TF2 = str_split_fixed(tmp.df$info.1...2, '-', 2)[,1]
  tmp.df$summit2 = as.numeric(str_split_fixed(tmp.df$info.1...2, '-', 2)[,2])
  tmp.df = tmp.df %>% dplyr::select(-1,-2)
  tmp.df = tmp.df %>% filter(TF1 != TF2)
  tmp.df$distances = abs(tmp.df$summit1 - tmp.df$summit2)
  tmp.df = tmp.df %>% group_by(TF1,TF2) %>% 
    summarize(distance = min(distances)) %>% 
    group_by(TF1,TF2) %>% 
    mutate(tf1x = min(TF1, TF2),
           tf2x = max(TF1, TF2)) %>% 
    ungroup() %>% 
    dplyr::select(-1, -2) %>% 
    unique()
  

  tmp.df$cytokine = Cytokine
  tmp.df = tmp.df[, c('tf1x', 'tf2x', 'cytokine', 'distance')]
  colnames(tmp.df) = c('TF1', 'TF2', 'cytokine', 'distance')
  peaks_df = rbind(peaks_df, tmp.df)

}

## Filter step
cutoff.distance = 50
peaks_df2 = peaks_df %>% group_by(TF1, TF2, cytokine) %>% summarize(distance = min(distance))

peaks_df2 = peaks_df2 %>% filter(distance <= cutoff.distance)
peaks_df2 = unique(peaks_df2)
peaks_df2 = peaks_df2 %>% 
  group_by(TF1, TF2, cytokine) %>% 
  mutate(name = paste(min(TF1,TF2), '-',max(TF1,TF2), ';', cytokine, sep = '' ),
         name2 = paste(min(TF1,TF2), '-',max(TF1,TF2), sep = '' )) %>% 
  unique()


## Y1H data with CHIP-seq data
merge(y1h_data, peaks_df2, by ='name') %>% dim()

# Y1H Network with 343 edges
test_network = graph_from_data_frame(y1h_data[,c('name2','DNA bait')])
#E(test_network)

# CHIP Network with 14462 edges
reference_network = graph_from_data_frame(peaks_df2[, c('name2', 'cytokine')])
#E(reference_network)

## True = CHIP edges
true = as_adjacency_matrix(reference_network,sparse = F)
true = melt(true)
true = true[true$value==1,]
true = paste0(true$Var1,true$Var2)

## Real_result
real_info = as_adjacency_matrix(test_network,sparse = F)
real_info = melt(real_info)
real_info = real_info[real_info$value==1,]
real_info = paste0(real_info$Var1,real_info$Var2)


numberofedgeswitching = 20000
iteration = 10000

results = c()

for (i in 1:iteration) {
  randomized_network = rewire(test_network, keeping_degseq(niter = numberofedgeswitching))
  randomized = as_adjacency_matrix(randomized_network,sparse = F)
  randomized = melt(randomized)
  randomized = randomized[randomized$value==1,]
  randomized = paste0(randomized$Var1,randomized$Var2)
  
  results = c(results,length(intersect(true,randomized)))
}

real_number = length(intersect(true, real_info))
results = data.frame(overlap=c(results, real_number),identity=c(rep('Randomized',iteration),'True'))
mean_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% mean()
sd_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% sd()
zscore = (real_number - mean_results)/ sd_results

ggplot(results,aes(x=overlap))+
  geom_histogram(binwidth = 1, color = 'black')+
  geom_vline(xintercept = results$overlap[results$identity=='True'],colour='red') +
  theme_bw() +
  ggtitle('Cooperativity - Same cell line')

#writexl::write_xlsx(results, path = 'Results_same_cell_lines_16_feb_cooperativity_50nts_distance.xlsx')
```

