---
title: "Randomization ey1h with chip-seq and py1h with cip-seq (TF-cytokine)"
author: "Luis Soto"
date: "2023-06-26"
output: html_document
---

```{r}
library(stringr)
library(dplyr)
library(readxl)
require('igraph')
require('reshape2')
require('ggplot2')
library(dplyr)
library(stringr)
library(writexl)
#BiocManager::install("TFBSTools")
library(readxl)
library(matrixStats)
library(stringi)
library(Biostrings)
library(TFBSTools)
library(TFMPvalue)
library(readr)
```


```{r}
cytokines.df = read_excel('Final events list 6FEB23.xlsx')

htfs = read.delim('all_tfs_chipseq.txt', sep = '\t')
htfs = rbind(htfs, data.frame(ID = 'AP2A', Uniprot = 'P05549'))
tfs_in_chip = htfs$ID %>% unique()

```


```{r}
ey1h = read_excel('py1h ey1h chip-seq overlap list for Luis.xlsx', sheet = 1)
ey1h = ey1h[, c('TF', 'Bait gene')]

peaks_data = read_excel('MACS2_Peaks_TFs_final_26_june.xlsx')
peaks_df_1 = peaks_data %>% dplyr::select(name, cytokine) %>% unique()
peaks_df_1$TF = peaks_df_1$name

py1h = read_excel('py1h ey1h chip-seq overlap list for Luis.xlsx', sheet = 2)
py1h$Cytokine = cytokines.df$`DNA bait`[match(py1h$`Bait gene`, cytokines.df$`DNA bait ID`)]
py1h = py1h[, c('TF', 'Cytokine')]

peaks_data = read_excel('MACS2_Peaks_TFs_final_16_feb.xlsx')
peaks_df_2 = peaks_data %>% dplyr::select(name, cytokine) %>% unique()
peaks_df_2$TF = peaks_df_2$name

ey1h$name = paste0(ey1h$TF, '-', ey1h$`Bait gene`) 
py1h$name = paste0(py1h$TF, '-', py1h$Cytokine)
peaks_df_1$name = paste0(peaks_df_1$TF, '-', peaks_df_1$cytokine)
peaks_df_2$name= paste0(peaks_df_2$TF, '-', peaks_df_2$cytokine)

```
```{r}
dim(ey1h)
dim(peaks_df_1)
dim(py1h)
dim(peaks_df_2)
```


```{r}

tfs_in_both = intersect(tfs_in_chip, ey1h$TF)
ey1h_filtered = ey1h[ey1h$TF %in% tfs_in_both,] 
write_xlsx(ey1h_filtered %>% filter(name %in% peaks_df_1$name), 'ey1h_intersection.xlsx')
ey1h_intersection = length(intersect(ey1h_filtered$name, peaks_df_1$name))

tfs_in_both = intersect(tfs_in_chip, py1h$TF)
py1h_filtered = py1h[py1h$TF %in% tfs_in_both,]
write_xlsx( py1h_filtered %>% filter(name %in% peaks_df_2$name), 'py1h_intersection.xlsx')
py1h_intersection = length(intersect(py1h_filtered$name, peaks_df_2$name))

print(paste('EY1H initial:', nrow(ey1h)))
print(paste('EY1H filtered (considering only TFs that have CHIP data):', nrow(ey1h_filtered)))
print(paste('EY1H pairs intersected with CHIP data:', ey1h_intersection))
print(paste('PY1H initial:', nrow(py1h)))
print(paste('PY1H filtered (considering only TFs that have CHIP data):', nrow(py1h_filtered)))
print(paste('PY1H pairs intersected with CHIP data:', py1h_intersection))
prop.test(x = c(ey1h_intersection, py1h_intersection), n = c(nrow(ey1h_filtered), nrow(py1h_filtered)) )

```

```{r}

### ey1h
tfs_in_both = intersect(tfs_in_chip, ey1h$TF)

ey1h = ey1h %>% filter(TF %in% tfs_in_both)


```


```{r}

# Y1H Network with 343 edges
test_network = graph_from_data_frame(ey1h_filtered[,c('TF','Bait gene')])

# CHIP Network with 14462 edges
reference_network = graph_from_data_frame(peaks_df_1[, c('TF', 'cytokine')])

## True = CHIP edges
true = as_adjacency_matrix(reference_network,sparse = F)
true = melt(true)
true = true[true$value==1,]
true = paste0(true$Var1,true$Var2)

## Real_result
real_info = as_adjacency_matrix(test_network,sparse = F)
real_info = melt(real_info)
real_info = real_info[real_info$value==1,]
real_info = paste0(real_info$Var1,real_info$Var2)
length(intersect(true, real_info))


numberofedgeswitching = 20000
iteration = 10000

results = c()

for (i in 1:iteration) {
  randomized_network = rewire(test_network, keeping_degseq(niter = numberofedgeswitching))
  randomized = as_adjacency_matrix(randomized_network,sparse = F)
  randomized = melt(randomized)
  randomized = randomized[randomized$value==1,]
  randomized = paste0(randomized$Var1,randomized$Var2)
  results = c(results,length(intersect(true,randomized)))
}

real_number = length(intersect(true, real_info))
results = data.frame(overlap=c(results, real_number),identity=c(rep('Randomized',iteration),'True'))
mean_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% mean()
sd_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% sd()
zscore = (real_number - mean_results)/ sd_results

results_ey1h = results


ggplot(results_ey1h,aes(x=overlap))+
  geom_histogram(binwidth = 1, color = 'black')+
  geom_vline(xintercept = results_ey1h$overlap[results_ey1h$identity=='True'],colour='red') +
  theme_bw() + 
  ggtitle('ey1h')


```

```{r}
### py1h
htfs = read.delim('all_tfs_chipseq.txt', sep = '\t')
htfs = rbind(htfs, data.frame(ID = 'AP2A', Uniprot = 'P05549'))
tfs_in_chip = htfs$ID %>% unique()

tfs_in_both = intersect(tfs_in_chip, py1h$TF)

py1h = py1h %>% filter(TF %in% tfs_in_both)
```

```{r}
# Y1H Network with 343 edges
test_network = graph_from_data_frame(py1h[,c('TF','Cytokine')])

# CHIP Network with 14462 edges
reference_network = graph_from_data_frame(peaks_df_2[, c('TF', 'cytokine')])

## True = CHIP edges
true = as_adjacency_matrix(reference_network,sparse = F)
true = melt(true)
true = true[true$value==1,]
true = paste0(true$Var1,true$Var2)

## Real_result
real_info = as_adjacency_matrix(test_network,sparse = F)
real_info = melt(real_info)
real_info = real_info[real_info$value==1,]
real_info = paste0(real_info$Var1,real_info$Var2)
length(intersect(true, real_info))


numberofedgeswitching = 20000
iteration = 10000

results = c()

for (i in 1:iteration) {
  randomized_network = rewire(test_network, keeping_degseq(niter = numberofedgeswitching))
  randomized = as_adjacency_matrix(randomized_network,sparse = F)
  randomized = melt(randomized)
  randomized = randomized[randomized$value==1,]
  randomized = paste0(randomized$Var1,randomized$Var2)
  results = c(results,length(intersect(true,randomized)))
}

real_number = length(intersect(true, real_info))
results = data.frame(overlap=c(results, real_number),identity=c(rep('Randomized',iteration),'True'))
mean_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% mean()
sd_results = results %>% filter(identity == 'Randomized') %>% dplyr::select(overlap) %>% unlist() %>% sd()
zscore = (real_number - mean_results)/ sd_results

results_py1h = results


ggplot(results_py1h,aes(x=overlap))+
  geom_histogram(binwidth = 1, color = 'black')+
  geom_vline(xintercept = results_py1h$overlap[results_py1h$identity=='True'],colour='red') +
  theme_bw() + 
  ggtitle('py1h')


```

```{r}
write_xlsx(results_ey1h, 'ey1h_randomization.xlsx')
write_xlsx(results_py1h, 'py1h_randomization.xlsx')


```